# Generated by Django 6.0.4 on 2026-05-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='estado_campania',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='campanias.estado_campania'),
            preserve_default=False,
        ),
    ]
