# Generated by Django 6.0.4 on 2026-09-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanias', '0002_convertir_estado_a_choice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campania',
            table='campanias',
        ),
    ]
