# Generated by Django 6.0.4 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campanias', '0003_alter_campania_table'),
        ('centros_salud', '0002_cargar_centros'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='centro_salud',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='campanias',
                to='centros_salud.centrosalud',
            ),
        ),
    ]
