# Generated by Django 6.0.4 on 2026-05-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposanguineo',
            name='factor',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gruposanguineo',
            name='grupo',
            field=models.CharField(max_length=5),
        ),
    ]
