# Generated by Django 6.0.4 on 2026-09-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inscripcion',
            table='inscripciones',
        ),
    ]
