# Generated by Django 6.0.4 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                (
                    'telefono',
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    'sitio_web',
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'db_table': 'centros_salud',
                'ordering': ['localidad', 'nombre'],
            },
        ),
    ]
