from decimal import Decimal

from django.db import migrations


CENTROS = [
    {
        'id': 1,
        'nombre': 'Banco Central de Sangre de la Provincia de Córdoba',
        'direccion': 'Rosario de Santa Fe 374',
        'barrio': 'Centro',
        'localidad': 'Córdoba',
        'telefono': '351 2480189',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/banco-de-sangre/',
        'latitud': Decimal('-31.4177671'),
        'longitud': Decimal('-64.1792522'),
    },
    {
        'id': 2,
        'nombre': 'Banco de Sangre Municipal',
        'direccion': 'Salta 480',
        'barrio': 'Centro',
        'localidad': 'Córdoba',
        'telefono': '0351 4276240 int. 4474/4475',
        'sitio_web': 'https://cordoba.gob.ar/donar-sangre-puede-salvar-hasta-cuatro-vidas/',
        'latitud': Decimal('-31.4121493'),
        'longitud': Decimal('-64.1763496'),
    },
    {
        'id': 3,
        'nombre': 'Banco de Sangre de la Universidad Nacional de Córdoba',
        'direccion': 'Enfermera Gordillo Gómez s/n, entre Bv. de la Reforma y Av. Valparaíso',
        'barrio': 'Ciudad Universitaria',
        'localidad': 'Córdoba',
        'telefono': '0351 4334121/28',
        'sitio_web': 'https://bancodesangre.turnos.unc.edu.ar/',
        'latitud': Decimal('-31.4379571'),
        'longitud': Decimal('-64.1878064'),
    },
    {
        'id': 4,
        'nombre': 'Fundación Banco Central de Sangre',
        'direccion': 'Caseros 1576',
        'barrio': 'Quinta Santa Ana',
        'localidad': 'Córdoba',
        'telefono': '0351 4807373',
        'sitio_web': 'https://www.donarencordoba.com.ar/',
        'latitud': Decimal('-31.4113956'),
        'longitud': Decimal('-64.2059516'),
    },
    {
        'id': 5,
        'nombre': 'Hospital Dr. Arturo Illia - Servicio de Hemoterapia',
        'direccion': 'Av. del Libertador 1450',
        'barrio': 'Cafferata',
        'localidad': 'Alta Gracia',
        'telefono': '03547 429282/85',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.6591224'),
        'longitud': Decimal('-64.4161881'),
    },
    {
        'id': 6,
        'nombre': 'Hospital Dr. José Antonio Ceballos - Servicio de Hemoterapia',
        'direccion': 'Gerónimo del Barco 1300',
        'barrio': 'Bell Ville',
        'localidad': 'Bell Ville',
        'telefono': '03534 421003/04/06',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-32.6168221'),
        'longitud': Decimal('-62.7037998'),
    },
    {
        'id': 7,
        'nombre': 'Hospital Dr. Pedro Vella - Servicio de Hemoterapia',
        'direccion': 'Rosario 300',
        'barrio': 'Corral de Bustos',
        'localidad': 'Corral de Bustos',
        'telefono': '03468 433974',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-33.2835410'),
        'longitud': Decimal('-62.1939697'),
    },
    {
        'id': 8,
        'nombre': 'Hospital Aurelio Crespo - Servicio de Hemoterapia',
        'direccion': 'Félix Cáceres s/n',
        'barrio': 'Cruz del Eje',
        'localidad': 'Cruz del Eje',
        'telefono': '03549 426747',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-30.7437265'),
        'longitud': Decimal('-64.7874548'),
    },
    {
        'id': 9,
        'nombre': 'Hospital Dr. Ernesto Romagosa - Servicio de Hemoterapia',
        'direccion': 'Colón 247',
        'barrio': 'Deán Funes',
        'localidad': 'Deán Funes',
        'telefono': '03521 479579 / 537161 / 426231',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-30.4240135'),
        'longitud': Decimal('-64.3563512'),
    },
    {
        'id': 10,
        'nombre': 'Hospital René Favaloro - Servicio de Hemoterapia',
        'direccion': 'Uruguay 537',
        'barrio': 'Huinca Renancó',
        'localidad': 'Huinca Renancó',
        'telefono': '02336 494107',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-34.8323721'),
        'longitud': Decimal('-64.3756257'),
    },
    {
        'id': 11,
        'nombre': 'Hospital Vicente Agüero - Servicio de Hemoterapia',
        'direccion': 'España 121',
        'barrio': 'Vicente Agüero',
        'localidad': 'Jesús María',
        'telefono': '03525 426703',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-30.9769867'),
        'longitud': Decimal('-64.0900763'),
    },
    {
        'id': 12,
        'nombre': 'Hospital San Antonio - Servicio de Hemoterapia',
        'direccion': 'Enrique Gauna 1251',
        'barrio': 'La Carlota',
        'localidad': 'La Carlota',
        'telefono': '03584 422295',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-33.4240280'),
        'longitud': Decimal('-63.3033394'),
    },
    {
        'id': 13,
        'nombre': 'Hospital Ramón J. Cárcano - Servicio de Hemoterapia',
        'direccion': 'Av. Juan Domingo Perón 20',
        'barrio': 'La Maitena',
        'localidad': 'Laboulaye',
        'telefono': '03385 453242',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-34.1405091'),
        'longitud': Decimal('-63.3920740'),
    },
    {
        'id': 14,
        'nombre': 'Hospital Abel Ayerza - Servicio de Hemoterapia',
        'direccion': 'Belgrano 350',
        'barrio': 'Marcos Juárez',
        'localidad': 'Marcos Juárez',
        'telefono': '03472 422820 / 422826 / 422828',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-32.6963534'),
        'longitud': Decimal('-62.0963009'),
    },
    {
        'id': 15,
        'nombre': 'Hospital Dr. Luis M. Bellodi - Servicio de Hemoterapia',
        'direccion': 'Av. Rossel 1800',
        'barrio': 'San Sebastián',
        'localidad': 'Mina Clavero',
        'telefono': None,
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.7433298'),
        'longitud': Decimal('-64.9991184'),
    },
    {
        'id': 16,
        'nombre': 'Nuevo Hospital San Antonio de Padua - Servicio de Hemoterapia',
        'direccion': 'Guardias Nacionales 1051',
        'barrio': 'San Antonio de Padua',
        'localidad': 'Río Cuarto',
        'telefono': '0358 4678700/03/72/75',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-33.1098399'),
        'longitud': Decimal('-64.3556313'),
    },
    {
        'id': 17,
        'nombre': 'Nuevo Hospital Provincial Brig. Gral. Juan Bautista Bustos - Servicio de Hemoterapia',
        'direccion': 'Estanislao del Campo y Amado Nervo',
        'barrio': 'Parque Industrial Leonardo Da Vinci',
        'localidad': 'Río Tercero',
        'telefono': '03571 410210 / WhatsApp 351 3102871',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-32.1849803'),
        'longitud': Decimal('-64.1365493'),
    },
    {
        'id': 18,
        'nombre': 'Hospital J. B. Iturraspe - Medicina Transfusional',
        'direccion': 'Dominga Cullen 450',
        'barrio': 'Parque',
        'localidad': 'San Francisco',
        'telefono': '03564 443722/18/19',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.4279816'),
        'longitud': Decimal('-62.0679246'),
    },
    {
        'id': 19,
        'nombre': 'Hospital Eva Perón - Banco de Sangre',
        'direccion': 'Ruta Provincial 5 km 90, esquina Dr. David Bustos',
        'barrio': 'Santa Rosa de Calamuchita',
        'localidad': 'Santa Rosa de Calamuchita',
        'telefono': '03546 426671 / WhatsApp 3546 402955 / 03546 426683/84',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-32.0627076'),
        'longitud': Decimal('-64.5304128'),
    },
    {
        'id': 20,
        'nombre': 'Hospital Dr. Ramón B. Mestre - Servicio de Hemoterapia',
        'direccion': 'Moisés Quinteros 548',
        'barrio': 'Villa Santa Rosa',
        'localidad': 'Villa Santa Rosa de Río Primero',
        'telefono': '03574 480914 / WhatsApp 3517 047999',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.1572030'),
        'longitud': Decimal('-63.4087868'),
    },
    {
        'id': 21,
        'nombre': 'Hospital José M. Urrutia - Servicio de Hemoterapia',
        'direccion': '3 de Febrero 324',
        'barrio': 'Unquillo',
        'localidad': 'Unquillo',
        'telefono': '0800 555 4141',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.2346069'),
        'longitud': Decimal('-64.3206411'),
    },
    {
        'id': 22,
        'nombre': 'Hospital Domingo Funes - Servicio de Hemoterapia',
        'direccion': 'Av. Domingo Funes s/n',
        'barrio': 'Villa Caeiro',
        'localidad': 'Santa María de Punilla',
        'telefono': '03541 489676/73/72/71',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.2967838'),
        'longitud': Decimal('-64.4535742'),
    },
    {
        'id': 23,
        'nombre': 'Hospital Provincial de Villa Dolores - Servicio de Hemoterapia',
        'direccion': 'Av. Belgrano 1800',
        'barrio': 'Villa Dolores',
        'localidad': 'Villa Dolores',
        'telefono': '03544 426437',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.9498789'),
        'longitud': Decimal('-65.1677567'),
    },
    {
        'id': 24,
        'nombre': 'Hospital Pasteur - Servicio de Hemoterapia',
        'direccion': 'Aldo Serrano esquina Buchardo',
        'barrio': 'Ramón Carrillo',
        'localidad': 'Villa María',
        'telefono': '0353 4619138/30',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-32.3939013'),
        'longitud': Decimal('-63.2589614'),
    },
    {
        'id': 25,
        'nombre': 'Hospital San Vicente de Paul - Servicio de Hemoterapia',
        'direccion': 'Bv. Sobremonte 550',
        'barrio': 'Del Molino',
        'localidad': 'Villa del Rosario',
        'telefono': '03573 424704 / 424706',
        'sitio_web': 'https://ministeriodesalud.cba.gov.ar/hospitales-y-centros-de-salud/',
        'latitud': Decimal('-31.5630144'),
        'longitud': Decimal('-63.5417909'),
    },
]


def cargar_centros(apps, schema_editor):
    CentroSalud = apps.get_model('centros_salud', 'CentroSalud')
    CentroSalud.objects.bulk_create(
        [CentroSalud(**centro) for centro in CENTROS]
    )


def eliminar_centros(apps, schema_editor):
    CentroSalud = apps.get_model('centros_salud', 'CentroSalud')
    CentroSalud.objects.filter(id__in=[centro['id'] for centro in CENTROS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('centros_salud', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_centros, eliminar_centros),
    ]
